defaults:
  - _self_
  - data_cfg: icv_data



test_icv: False
test_icl: False
test_clip_icv: True
bs: 1
test_num: -1
few_shot_list: [1, 2, 4, 8, 16, 32]

run_name: fv_vqav2
result_dir: ${oc.env:RESULT_DIR}
device: 'cuda:3'
start: 0
end: 32
model_name_or_path: "${oc.env:MODEL_CPK_DIR}/idefics-9b"
clip_path: "${oc.env:MODEL_CPK_DIR}/clip-vit-base-patch32"

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
