defaults:
  - _self_
  - data_cfg: icv_data
  - icv_module: icv_module
  - trainer: zero2

seed: 426

run_name: "clip_test"

model_name_or_path: "${oc.env:MODEL_CPK_DIR}/idefics-9b"
# model_name: "HuggingFaceM4/tiny-random-idefics"
model_name: "idefics-9b"
model_cpk_dir: ${oc.env:MODEL_CPK_DIR}
result_dir: ${oc.env:RESULT_DIR}


hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
